backend:
  name: git-gateway
  branch: master

media_folder: "assets/img/uploads"

publish_mode: editorial_workflow

collections:
  # POSTS
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Hero", name: "hero", widget: "image"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
    # services
  - name: "service"
    label: "Service"
    folder: "_services"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "service"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
  # specialists
  - name: "specialist"
    label: "Specialist"
    folder: "_specialists"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "service"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}  
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Text, name: text, widget: string}
              - {label: Url, name: url, widget: string}
      - label: "Info"
        name: "info"
        file: "_data/info.yml"
        fields:
          - label: "Info Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Text, name: text, widget: string}     
   